[build-system]
requires = ["hatch"]
build-backend = "hatchling"

[project]
name = "spinbox"
version = "0.1.0"
authors = [
    { name="Jordan M. R. Fox", email="jordanmrfox@gmail.com" },
]
description = "Tools for imaginary-time propagation in nuclear Monte Carlo calculations"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy~=1.24.3",
    "matplotlib~=3.7.2",
    "scipy~=1.10.0",
    "tqdm~=4.66.1",
]
license = {text = "MIT"}

[project.urls]
"Homepage" = "https://github.com/jmrfox/spinbox"
