[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "spinbox"
dynamic = ["version"]
description = 'Tools for imaginary-time propagation in nuclear Monte Carlo calculations'
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
keywords = []
authors = [
  { name = "jfox", email = "jfox@anl.gov" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = []

[project.urls]
Documentation = "https://github.com/jfox/spinbox#readme"
Issues = "https://github.com/jfox/spinbox/issues"
Source = "https://github.com/jfox/spinbox"

[tool.hatch.version]
path = "src/spinbox/__about__.py"

[tool.hatch.envs.types]
extra-dependencies = [
  "mypy>=1.0.0",
]
[tool.hatch.envs.types.scripts]
check = "mypy --install-types --non-interactive {args:src/spinbox tests}"

[tool.coverage.run]
source_pkgs = ["spinbox", "tests"]
branch = true
parallel = true
omit = [
  "src/spinbox/__about__.py",
]

[tool.coverage.paths]
spinbox = ["src/spinbox", "*/spinbox/src/spinbox"]
tests = ["tests", "*/spinbox/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
